language: python
python:
  - "2.7"
install:
  - pip install fabric
  - pip install requests
  - pip install python-ldap
  - pip install pywebdav
  - pip install vobject==0.8.1c
  - pip install pytz
  - pip install python-stdnum

  - fab setup
script: 
  - fab runtests
